### ISSUE TITLE
typo in PerspectiveMotionBehabiour class

### ISSUE THREAD

**Issue by sammy2407** [yannickl/Perspective#2]
Hey, there is a typo in this class name. 
It must be PerspectiveMotionBehaviour. So that while adding the behaviour, we can use the name "perspectiveView.addBehaviour(PerspectiveMotionBehaviour())" instead of "perspectiveView.addBehaviour(PerspectiveMotionBehabiour())"

**Comment by yannickl** [comment]
Oh thanks for spotting that!
